server:
  port: 20080
spring:
  datasource:
    url: jdbc:mysql://sinfonia.top:3306/test?useUnicode=true&amp;characterEncoding=utf8&amp;allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: test
    password: 123456
  rabbitmq:
    host: sinfonia.top
    port: 5672
    username: test
    password: test
mybatis:
  mapper-locations: classpath:sql/mapper/*Mapper.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://sinfonia.top:20089/eureka/
sinfonia:
  uc:
    info: Sinfonia UC Dev