server:
  port: 20080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sinfonia_uc?useUnicode=true&amp;characterEncoding=utf8&amp;allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: sinfonia_uc_wr
    password: HdjcoK{f*fk@k-13
  rabbitmq:
    host: sinfonia.top
    port: 15672
    username: test
    password: 123456
mybatis:
  mapper-locations: classpath:sql/mapper/*Mapper.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://sinfonia.top:20089/eureka/